[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
aggressive = 2

[tool.mypy]
disallow_untyped_calls = true
mypy_path = "stubs"
packages = "bobcat"

[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylint."MESSAGES CONTROL"]
disable = "global-statement"

[tool.pylint.TYPECHECK]
# Don't check on classes with attributes added a runtime
ignored-classes = "FeedGenerator,FeedEntry"
