from datetime import datetime
from typing import AnyStr
from feedgen.ext.podcast import PodcastExtension

class FeedEntry:
    def id(self, id: str) -> None: ...
    def title(self, title: str) -> None: ...
    def description(self, description:str) -> None: ...
    def enclosure(self, url: str, length: str, type: str) -> None: ...
    def published(self, published: datetime) -> None: ...
    def link(self, href: str) -> None: ...
    podcast: PodcastExtension
