from datetime import datetime
from feedgen.ext.podcast import PodcastExtension
from feedgen.entry import FeedEntry

class FeedGenerator:
    podcast: PodcastExtension
    def load_extension(self, extension: str) -> None: ...
    def title(self, title: str) -> None: ...
    def description(self, description: str) -> None: ...
    def logo(self, logo_url: str) -> None: ...
    def link(self, href: str, rel: str) -> None: ...
    def language(self, lang: str) -> None: ...
    def pubDate(self, publication_date: datetime) -> None: ...
    def lastBuildDate(self, build_date: datetime) -> None: ...
    def add_entry(self) -> FeedEntry: ...
    def rss_file(self, filename: str, pretty: bool) -> None: ...